from pathlib import Path
from typing import Literal

from pydantic import BaseModel, Field


class AgentRequest(BaseModel):
    """Represent a normalized request submitted to the agent service."""

    schema_ver: str = "v1"

    channel_id: str
    user_id: str
    request_id: str
    text: str | None = None
    file_path: Path | None = None

    workspace: Path | None = None


class Artifact(BaseModel):
    """Describe an artifact generated by the agent for a task."""

    path: Path
    name: str
    mime_type: str
    safe_to_share: bool = False


class AgentResult(BaseModel):
    """Represent the final state and outputs of an agent execution."""

    text: str | None = None
    artifacts: list[Artifact] = Field(default_factory=list)
    status: Literal["completed", "waiting_user", "failed"]
    error: str | None = None
